"""Auto-generated Add S3 data exfiltration detector.

Detect suspicious S3 access patterns: bulk downloads, cross-account access, and public
    object creation.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

__all__ = ["S3DataExfiltrationDetector"]

logger = logging.getLogger(__name__)


class AlertSeverity(Enum):
    """Alert severity levels."""

    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


@dataclass
class Alert:
    """A security alert generated by a detection rule.

    Attributes:
        rule_id: Detection rule identifier.
        title: Alert title.
        severity: Alert severity.
        source: Source of the event.
        details: Detailed description.
        mitre_tactic: MITRE ATT&CK tactic.
        mitre_technique: MITRE ATT&CK technique ID.
    """

    rule_id: str
    title: str
    severity: AlertSeverity
    source: str
    details: str
    mitre_tactic: str = ""
    mitre_technique: str = ""


@dataclass
class S3DataExfiltrationDetector:
    """Detection rule for Add S3 data exfiltration detector.

    Detect suspicious S3 access patterns: bulk downloads, cross-account access, and public
    object creation.

    Attributes:
        alerts: Alerts generated during the last analysis.
    """

    alerts: list[Alert] = field(default_factory=list)

    def analyse(self, events: list[dict[str, Any]]) -> list[Alert]:
        """Analyse events for suspicious patterns.

        Args:
            events: List of cloud event dicts (mock CloudTrail format).

        Returns:
            List of generated alerts.
        """
        self.alerts.clear()
        logger.info("Running %s detection", self.__class__.__name__)

        for event in events:
            self._evaluate_event(event)

        logger.info("Detection complete — %d alert(s)", len(self.alerts))
        return list(self.alerts)

    def _evaluate_event(self, event: dict[str, Any]) -> None:
        """Evaluate a single event against detection logic."""
        # Check for high-risk API calls
        action = event.get("action", "")
        principal = event.get("principal", "unknown")
        source_ip = event.get("source_ip", "")

        high_risk_actions = {
            "CreatePolicyVersion",
            "AttachUserPolicy",
            "AttachRolePolicy",
            "PutBucketPolicy",
            "CreateAccessKey",
            "AssumeRole",
        }

        if action in high_risk_actions:
            self.alerts.append(
                Alert(
                    rule_id="DETECTION003-001",
                    title=f"High-risk API call: {action}",
                    severity=AlertSeverity.HIGH,
                    source=principal,
                    details=(
                        f"Principal '{principal}' invoked high-risk action "
                        f"'{action}' from {source_ip}"
                    ),
                    mitre_tactic="Privilege Escalation",
                    mitre_technique="T1078",
                )
            )

        # Check for unusual source IPs
        if source_ip and not source_ip.startswith(("10.", "172.16.", "192.168.")):
            if event.get("is_console_login", False):
                self.alerts.append(
                    Alert(
                        rule_id="DETECTION003-002",
                        title="Console login from external IP",
                        severity=AlertSeverity.MEDIUM,
                        source=principal,
                        details=(f"Console login by '{principal}' from external IP {source_ip}"),
                        mitre_tactic="Initial Access",
                        mitre_technique="T1078",
                    )
                )
