# Add Terraform security-group module with CIS presets
#
# Create reusable security-group module with named rule presets for web, database, and
    management tiers following CIS benchmarks.
#
# Auto-generated by Cloud Security Lab Agent

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# --- Main Resource ---

resource "aws_example" "this" {
  # TODO: Replace with actual resource configuration

  tags = merge(var.tags, {
    ManagedBy   = "terraform"
    SecurityLab = "true"
    Module      = "terraform-004"
  })
}
