# Add AWS Security Group Unrestricted Ingress Detector
#
# Implement a new detector to identify AWS Security Groups allowing unrestricted inbound
    access (0.0.0.0/0) on sensitive ports (22, 3389, 3306, 5432, 27017, etc.). This
    detector will integrate with the existing detectors module, support both
    CloudFormation and Terraform IaC scanning, and map to CIS AWS Foundations Benchmark
    v2.0.0 rule 4.1 and 4.2.
#
# Auto-generated by Cloud Security Lab Agent

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# --- Main Resource ---

resource "aws_example" "this" {
  # TODO: Replace with actual resource configuration

  tags = merge(var.tags, {
    ManagedBy   = "terraform"
    SecurityLab = "true"
    Module      = "detector-aws-sg-unrestricted-ingress"
  })
}
